spring:
  datasource:
   url: jdbc:h2:mem:testdb
   driverClassName: org.h2.Driver
   username: sa
   password: ''
  h2:
   console:
    enabled: true
  jpa:
   hibernate:
    ddl-auto: update
   show-sql: true
  config:
   import:
    - "application_qa.yml"
    - "application_prod.yml"
  profiles:
   active: "qa"   
accounts:
  message: "Welcome to HDFC Bank accounts related local APIs "
  contactDetails:
    name: "Amol Patil - Manager"
    email: "amol@hdfc.com"
  onCallSupport:
    - (020) 1234567890
    