spring:
  config:
    activate:
       on-profile: "prod"

loans:
  message: "Welcome to HDFC Bank Loans Prod related local APIs "
  contactDetails:
    name: "Sid Patil - Prod Manager"
    email: "sid@hdfc.com"
  onCallSupport:
    - (020) 3456789012