spring:
  config:
    activate:
       on-profile: "prod"
   
accounts:
  message: "Welcome to HDFC Bank accounts Production related local APIs "
  contactDetails:
    name: "Amol Patil -PROD Manager"
    email: "amol@hdfc.com"
  onCallSupport:
    - (020) 1234567890
    