services:
 accounts:
  image: amolpatil2012/accounts:s5
  container_name: accounts-service
  ports: 
   - "8080:8080"
  networks:
   - app-network
 loans:
  image: amolpatil2012/loans:s5
  container_name: loans-service
  ports:
   - "8090:8090"
  networks:
   - app-network
 cards:
  image: amolpatil2012/cards:s5
  container_name: cards-service
  ports:
   - "9000:9000"
  networks:
   - app-network
networks:
 app-network:
  driver: bridge